<?php

namespace App\Filament\Resources\FactusolProducts\Tables;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class FactusolProductsTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('CODART')
                    ->label('CODART')
                    ->sortable()
                    ->searchable(),
                TextColumn::make('EANART')
                    ->label('EANART')
                    ->sortable()
                    ->searchable(),
                TextColumn::make('EQUART')
                    ->label('EQUART')
                    ->sortable()
                    ->searchable(),
                TextColumn::make('CCOART')
                    ->label('CCOART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('FAMART')
                    ->label('FAMART')
                    ->searchable(),
                TextColumn::make('ACTSTO')
                    ->label('ACTSTO')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('DESART')
                    ->label('DESART')
                    ->searchable(),
                TextColumn::make('DEEART')
                    ->label('DEEART')
                    ->searchable(),
                TextColumn::make('DETART')
                    ->label('DETART')
                    ->searchable(),
                TextColumn::make('PHAART')
                    ->label('PHAART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('TIVART')
                    ->label('TIVART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('PCOART')
                    ->label('PCOART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('DT0ART')
                    ->label('DT0ART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('DT1ART')
                    ->label('DT1ART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('DT2ART')
                    ->label('DT2ART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('FALART')
                    ->label('FALART')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('MDAART')
                    ->label('MDAART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('UBIART')
                    ->label('UBIART')
                    ->searchable(),
                TextColumn::make('UELART')
                    ->label('UELART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('UPPART')
                    ->label('UPPART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('DIMART')
                    ->label('DIMART')
                    ->searchable(),
                TextColumn::make('MEMART')
                    ->label('MEMART')
                    ->searchable(),
                TextColumn::make('OBSART')
                    ->label('OBSART')
                    ->searchable(),
                TextColumn::make('NPUART')
                    ->label('NPUART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('NIAART')
                    ->label('NIAART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('COMART')
                    ->label('COMART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('CP1ART')
                    ->label('CP1ART')
                    ->searchable(),
                TextColumn::make('CP2ART')
                    ->label('CP2ART')
                    ->searchable(),
                TextColumn::make('CP3ART')
                    ->label('CP3ART')
                    ->searchable(),
                TextColumn::make('REFART')
                    ->label('REFART')
                    ->searchable(),
                TextColumn::make('DLAART')
                    ->label('DLAART')
                    ->searchable(),
                TextColumn::make('IPUART')
                    ->label('IPUART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('NCCART')
                    ->label('NCCART')
                    ->searchable(),
                TextColumn::make('CUCART')
                    ->label('CUCART')
                    ->searchable(),
                TextColumn::make('CANART')
                    ->label('CANART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('IMGART')
                    ->label('IMGART')
                    ->searchable(),
                TextColumn::make('SUWART')
                    ->label('SUWART')
                    ->sortable(),
                TextColumn::make('DELART')
                    ->label('DELART')
                    ->searchable(),
                TextColumn::make('DEWART')
                    ->label('DEWART')
                    ->searchable(),
                TextColumn::make('MEWART')
                    ->label('MEWART')
                    ->searchable(),
                TextColumn::make('CSTART')
                    ->label('CSTART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('IMWART')
                    ->label('IMWART')
                    ->searchable(),
                TextColumn::make('STOART')
                    ->label('STOART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('FUMART')
                    ->label('FUMART')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('PESART')
                    ->label('PESART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('FTEART')
                    ->label('FTEART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ACOART')
                    ->label('ACOART')
                    ->searchable(),
                TextColumn::make('GARART')
                    ->label('GARART')
                    ->searchable(),
                TextColumn::make('UMEART')
                    ->label('UMEART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('TMOART')
                    ->label('TMOART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('CONART')
                    ->label('CONART')
                    ->searchable(),
                TextColumn::make('TIV2ART')
                    ->label('TIV2ART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('DE1ART')
                    ->label('DE1ART')
                    ->searchable(),
                TextColumn::make('DE2ART')
                    ->label('DE2ART')
                    ->searchable(),
                TextColumn::make('DE3ART')
                    ->label('DE3ART')
                    ->searchable(),
                TextColumn::make('DFIART')
                    ->label('DFIART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('RPUART')
                    ->label('RPUART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('RPFART')
                    ->label('RPFART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('RCUART')
                    ->label('RCUART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('RCFART')
                    ->label('RCFART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('MECART')
                    ->label('MECART')
                    ->searchable(),
                TextColumn::make('DSCART')
                    ->label('DSCART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('AMAART')
                    ->label('AMAART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('CAEART')
                    ->label('CAEART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('UFSART')
                    ->label('UFSART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('IMFART')
                    ->label('IMFART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('PFIART')
                    ->label('PFIART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('MPTART')
                    ->label('MPTART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('CP4ART')
                    ->label('CP4ART')
                    ->searchable(),
                TextColumn::make('CP5ART')
                    ->label('CP5ART')
                    ->searchable(),
                TextColumn::make('ORDART')
                    ->label('ORDART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('UEQART')
                    ->label('UEQART')
                    ->searchable(),
                TextColumn::make('DCOART')
                    ->label('DCOART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('FAVART')
                    ->label('FAVART')
                    ->searchable(),
                TextColumn::make('DSTART')
                    ->label('DSTART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('VEWART')
                    ->label('VEWART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('URAART')
                    ->label('URAART')
                    ->searchable(),
                TextColumn::make('VMPART')
                    ->label('VMPART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('UR1ART')
                    ->label('UR1ART')
                    ->searchable(),
                TextColumn::make('UR2ART')
                    ->label('UR2ART')
                    ->searchable(),
                TextColumn::make('UR3ART')
                    ->label('UR3ART')
                    ->searchable(),
                TextColumn::make('CN8ART')
                    ->label('CN8ART')
                    ->searchable(),
                TextColumn::make('OCUART')
                    ->label('OCUART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('RSVART')
                    ->label('RSVART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('NVSART')
                    ->label('NVSART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('DEPART')
                    ->label('DEPART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('SDEART')
                    ->label('SDEART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('CASART')
                    ->label('CASART')
                    ->searchable(),
                TextColumn::make('HALART')
                    ->label('HALART')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('UALART')
                    ->label('UALART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('HUMART')
                    ->label('HUMART')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('UUMART')
                    ->label('UUMART')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('created_at')
                    ->label(__('filament.resources.created_at'))
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->label(__('filament.resources.updated_at'))
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->defaultSort('created_at', 'desc')
            ->filters([
                //
            ])
            ->recordActions([
                // EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    // DeleteBulkAction::make(),
                ]),
            ]);
    }
}
