<?php

namespace App\Filament\Resources\FactusolProducts\Schemas;

use Filament\Forms\Components\DateTimePicker;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Schema;

class FactusolProductForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('CODART')
                    ->required(),
                TextInput::make('EANART'),
                TextInput::make('EQUART'),
                TextInput::make('CCOART')
                    ->numeric(),
                TextInput::make('FAMART'),
                TextInput::make('ACTSTO')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('DESART'),
                TextInput::make('DEEART'),
                TextInput::make('DETART'),
                TextInput::make('PHAART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('TIVART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('PCOART')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('DT0ART')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('DT1ART')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('DT2ART')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                DateTimePicker::make('FALART'),
                TextInput::make('MDAART')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('UBIART'),
                TextInput::make('UELART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('UPPART')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('DIMART'),
                TextInput::make('MEMART'),
                TextInput::make('OBSART'),
                TextInput::make('NPUART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('NIAART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('COMART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('CP1ART'),
                TextInput::make('CP2ART'),
                TextInput::make('CP3ART'),
                TextInput::make('REFART'),
                TextInput::make('DLAART'),
                TextInput::make('IPUART')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('NCCART'),
                TextInput::make('CUCART'),
                TextInput::make('CANART')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('IMGART'),
                TextInput::make('SUWART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('DELART'),
                TextInput::make('DEWART'),
                TextInput::make('MEWART'),
                TextInput::make('CSTART')
                    ->required()
                    ->numeric()
                    ->default(3),
                TextInput::make('IMWART'),
                TextInput::make('STOART')
                    ->required()
                    ->numeric()
                    ->default(0),
                DateTimePicker::make('FUMART'),
                TextInput::make('PESART')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('FTEART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('ACOART'),
                TextInput::make('GARART'),
                TextInput::make('UMEART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('TMOART')
                    ->required()
                    ->numeric()
                    ->default(1),
                TextInput::make('CONART'),
                TextInput::make('TIV2ART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('DE1ART'),
                TextInput::make('DE2ART'),
                TextInput::make('DE3ART'),
                TextInput::make('DFIART')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('RPUART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('RPFART')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('RCUART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('RCFART')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('MECART'),
                TextInput::make('DSCART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('AMAART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('CAEART')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('UFSART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('IMFART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('PFIART')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('MPTART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('CP4ART'),
                TextInput::make('CP5ART'),
                TextInput::make('ORDART')
                    ->required()
                    ->numeric()
                    ->default(999999),
                TextInput::make('UEQART'),
                TextInput::make('DCOART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('FAVART'),
                TextInput::make('DSTART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('VEWART')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('URAART'),
                TextInput::make('VMPART')
                    ->required()
                    ->numeric()
                    ->default(0.0),
                TextInput::make('UR1ART'),
                TextInput::make('UR2ART'),
                TextInput::make('UR3ART'),
                TextInput::make('CN8ART'),
                TextInput::make('OCUART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('RSVART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('NVSART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('DEPART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('SDEART')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('CASART'),
                DateTimePicker::make('HALART'),
                TextInput::make('UALART')
                    ->required()
                    ->numeric()
                    ->default(0),
                DateTimePicker::make('HUMART'),
                TextInput::make('UUMART')
                    ->required()
                    ->numeric()
                    ->default(0),
            ]);
    }
}
